#development version of configurations
server:
  port: 8083

#database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
#Jpa and hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
